apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-deployment
  labels:
    deployment.environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment.environment: production
    spec:
      containers:
        - name: demo1
          image: jerryworld/demo1-main:7e0b47f95cf20ea9d9e11b55350975e1a349cc53
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      imagePullSecrets:
        - name: docker-hub-secret
