apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka-main          # 네 네임스페이스
spec:
  type: NodePort
  selector:
    app: kafka                   # StatefulSet pod label이랑 맞춰야 함
  ports:
    - name: external
      port: 9092                 # 서비스 포트
      targetPort: 9092           # 컨테이너 포트
      nodePort: 30092            # 호스트에서 사용할 포트
