apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7.0
          ports:
            - containerPort: 9092
              name: plaintext
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LISTENERS
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            - name: KAFKA_LOG_RETENTION_HOURS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LOG_RETENTION_HOURS
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 5Gi
