apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9.2
          ports:
            - containerPort: 2181
              name: client
          env:
            - name: ZOO_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: ZOOKEEPER_CLIENT_PORT
            - name: ZOO_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: ZOOKEEPER_TICK_TIME
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
