apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
    service.name: demo
    service.group: jerryworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        service.name: demo
        service.group: jerrywrold
