apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    deployment.environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment.environment: production
    spec:
      containers:
        - name: demo
          image: jerryworld/demo:ae0ab6947172a85192fdfc395023a513b7a28ab44de4785bb14ea1f687877c73c57017850e70c68b8d0700dd1c546bd703e63e4c
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      imagePullSecrets:
        - name: docker-hub-secret
