apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    deployment.environment: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment.environment: production
    spec:
      containers:
        - name: demo
          image: jerryworld/demo-main:64155a630e094842f9eb0f672cf06c79c4d88d63
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      imagePullSecrets:
        - name: docker-hub-secret
