apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    deployment.environment: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment.environment: development
    spec:
      containers:
        - name: demo
          image: jerryworld/demo:aed4cd0f
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

      imagePullSecrets:
        - name: docker-hub-secret
