apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-deployment
  labels:
    deployment.environment: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment.environment: development
    spec:
      containers:
        - name: demo1-dev
          image: jerryworld/demo1-dev:d6c0604c4a9dbd0e15073d95ddd2133b2b42f98b
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev