apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-deployment
  labels:
    deployment.environment: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment.environment: development
    spec:
      containers:
        - name: demo1-dev
          image: jerryworld/demo1-dev:0a4f7f3808168a8c9e9d64ee9b0ec532094c082c
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev